apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: user
        image: lamtran59/user:latest
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: user-env-configmap
