name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image for user
        uses: docker/build-push-action@v2
        with:
          context: ./apps/user
          push: true
          tags: lamtran59/user:latest

      - name: Build and push Docker image for auth
        uses: docker/build-push-action@v2
        with:
          context: ./apps/auth
          push: true
          tags: lamtran59/auth:latest

      - name: Set up kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/kubectl

      - name: Set up Kubernetes config
        env:
          KUBECONFIG_CONTENTS: ${{ secrets.KUBECONFIG }}
        run: |
          mkdir -p $HOME/.kube
          echo "$KUBECONFIG_CONTENTS" > $HOME/.kube/config

      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/user-deployment user=lamtran59/user:latest
          kubectl set image deployment/auth-deployment auth=lamtran59/auth:latest
